set-option -g default-shell /bin/fish

set -g mouse on

# Plugin stuff

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'

bind-key n split-window -h -p 40

run '~/.tmux/plugins/tpm/tpm'
