vim.cmd("set number")
vim.cmd("set autoindent")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set smarttab")
vim.cmd("set softtabstop=4")
vim.cmd("syntax off")
vim.cmd("set mouse=")
vim.cmd("set linebreak")
vim.cmd("set noeol nofixeol")
