"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[╰─ ✦](bold yellow)'
error_symbol = "[╰─ 󰋔](bold red)"

[git_branch]
symbol = " "

[package]
symbol = "󰏖 "

[c]
symbol = " "

[python]
symbol = "󰌠 "
