"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[time]
time_format = "%T"
format = '╰[\($time\)]($style)'
style = "bright-white"
disabled = false

[character]
success_symbol = '[─ ✦](bold yellow)'
error_symbol = "[─ 󰋔](bold red)"

[git_branch]
symbol = " "

[package]
symbol = "󰏖 "

[c]
symbol = " "

[python]
symbol = "󰌠 "

[golang]
symbol = " "

format = """
$time\
$directory\
$git_branch $git_status\
$character
""""
